version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]

exclude_patterns = [
  "frontend/src/components/ui/**",
  "frontend/src/hooks/use-mobile.ts",
  "frontend/src/routeTree.gen.ts",
]